export const OPEN_ADMIN_SIDEBAR = "OPEN_ADMIN_SIDEBAR";
export const CLOSE_ADMIN_SIDEBAR = "CLOSE_ADMIN_SIDEBAR";

export const ADMIN_SIDEBAR_SLIDE_IN = "ADMIN_SIDEBAR_SLIDEIN";
export const ADMIN_SIDEBAR_SLIDE_OUT = "ADMIN_SIDEBAR_SLIDE_OUT";
