export const OPEN_AVATAR_SUBMENU = "OPEN_AVATAR_SUBMENU";
export const CLOSE_AVATAR_SUBMENU = "CLOSE_AVATAR_SUBMENU";

export const OPEN_NOTIFICATION_SUBMENU = "OPEN_NOTIFICATION_SUBMENU";
export const CLOSE_NOTIFICATION_SUBMENU = "CLOSE_NOTIFICATION_SUBMENU";
